version: '3'

services:
  racoonbrothers:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "9091:9091"
    environment:
      DB_URL: jdbc:mysql://raccoonbrothers_backend_db:3306/raccoonbrothers?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      raccoonbrothers_backend_db:
        condition: service_healthy
    networks:
      - raccoonbrothers_network

  raccoonbrothers_backend_db:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: raccoonbrothers
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    networks:
      - raccoonbrothers_network

networks:
  raccoonbrothers_network:
    external: true
